# Generated by Django 3.2.13 on 2022-06-29 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20220630_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='dob',
            field=models.DateField(blank=True, max_length=8, null=True),
        ),
    ]
